services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent_bit
    restart: unless-stopped
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
    command: [
      "/fluent-bit/bin/fluent-bit",
      "-c", "/fluent-bit/etc/fluent-bit.conf"
    ]

